CREATE TABLE IF NOT EXISTS "Tags" (
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("Name")
);
CREATE TABLE IF NOT EXISTS "Recipies" (
	"ID_Rec"	TEXT NOT NULL,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("ID_Rec")
);
CREATE TABLE IF NOT EXISTS "RecHasTag" (
	"ID"	INTEGER,
	"ID_Rec"	TEXT NOT NULL,
	"Name"	TEXT NOT NULL,
	FOREIGN KEY("Name") REFERENCES "Tags"("Name"),
	FOREIGN KEY("ID_Rec") REFERENCES "Recipies"("ID_Rec"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);

